import os
import cv2

DEFAULT_SERVER_URL = 'https://olympik.fun'
DEFAULT_CAMERA_NAME = 'Камера'
DEFAULT_DEVICE_ID = 0
DEFAULT_FPS = 60
DEFAULT_JPEG_QUALITY = 40
VIDEO_WIDTH = 480
VIDEO_HEIGHT = 360
FACE_RECOGNITION_INTERVAL = 0.5
OBJECT_DETECTION_INTERVAL = 0.5

NUM_THREADS = os.cpu_count() or 4
cv2.setNumThreads(NUM_THREADS)

ULTRASOUND_ENABLED = True
ULTRASOUND_FREQUENCY = 18000
ULTRASOUND_DURATION = 2.0

DRAW_FACE_BOXES = True
DRAW_OBJECT_BOXES = True
FACE_BOX_COLOR_KNOWN = (0, 255, 0)
FACE_BOX_COLOR_UNKNOWN = (0, 0, 255)
OBJECT_BOX_COLOR = (255, 255, 0)
BOX_THICKNESS = 2
FONT_SCALE = 0.6

